language: node_js
node_js:
  - "5"
before_script:
  - chmod +x scripts/deploy.sh
script: 
- gulp
notifications:
  slack: nationalrailviewer:gFFj43AQ9ylarHMZzY4cfljZ
deploy: 
skip_cleanup: true
on:
    branch: master
after_success:
- scripts/deploy.sh